### ISSUE TITLE
[SUGGESTION] Allow downloads to be picked up by external download managers

### ISSUE THREAD

**Issue by rishav394** [Presto412/Enhancer-for-VIT-Vellore-Academics#1]
The title says it. On batch selecting files and downloading, Files get downloaded from default chrome download client even though I try to force it with IDM using the force keys for IDM. 
So it'll probably be great if it lets external download managers to pick up downloads.

**Comment by Presto412** [comment]
It's not possible to do so, because the chrome downloads API works only for
the default DM. Moreover, if I were to hard-code this, IDM would have to
have a message listener that I could send from one to another. Closing the
issue.
