### ISSUE TITLE
Auto Naming of the files disabled after the previous update

### ISSUE THREAD

**Issue by AryaPatel1111** [Presto412/Enhancer-for-VIT-Vellore-Academics#11]
Automatic file naming convention isn't working after the previous update you rolled out. Please fix that.

**Comment by Presto412** [comment]
Published the fix to the webstore, might take few days to go live - https://github.com/Presto412/Enhancer-for-VIT-Vellore-Academics/pull/10

**Comment by Presto412** [comment]
Live on the web store.
