### ISSUE TITLE
Captcha is back

### ISSUE THREAD

**Issue by BRO3886** [Presto412/Enhancer-for-VIT-Vellore-Academics#8]
* sometimes the site loads with recaptcha, other times it falls back to the old captcha, 
* if their could be a switch on the extension which can enable/disable the captcha script it'll be great

![image](https://user-images.githubusercontent.com/39856034/121332860-e22d4780-c935-11eb-89e8-861701135283.png)

**Comment by Presto412** [comment]
Will do

**Comment by Presto412** [comment]
Done via this [commit ](https://github.com/Presto412/Enhancer-for-VIT-Vellore-Academics/commit/305f499fd5ddf12715240908a7fcf65fd7173e4b)
